import { IoBookOutline } from "react-icons/io5";
import { LuFileStack, LuLayoutDashboard } from "react-icons/lu";
import { MdOutlineLocalOffer } from "react-icons/md";
import { PiStudent } from "react-icons/pi";
import { Course, DummyBatches, DummyInstructors, DummyStudent} from "./types";

export const adminSidebarLinks = [
  {
    label: "Dashboard",
    link: "/admin/dashboard",
    icon: LuLayoutDashboard,
  },
  {
    label: "Courses",
    link: "/admin/courses",
    icon: IoBookOutline,
  },
  {
    label: "Modules",
    link: "/admin/modules",
    icon: LuFileStack,
  },
  {
    label: "Offers",
    link: "/admin/offers",
    icon: MdOutlineLocalOffer,
  },
  {
    label: "Students",
    link: "/admin/students",
    icon: PiStudent,
  },
];

export const sampleMeetings = [
  {
    _id: "1",
    date: "2025-05-01",
    course: "JavaScript Bootcamp",
    module: "Promise",
    batch: "Batch A",
    time: "10:00 AM",
  },
  {
    _id: "2",
    date: "2025-05-01",
    course: "Python Basics",
    module: "Datatypes",
    batch: "Batch B",
    time: "2:00 PM",
  },
  {
    _id: "3",
    date: "2025-05-04",
    course: "React Hooks",
    module: "useState",
    batch: "Batch C",
    time: "11:00 AM",
  },
  {
    _id: "4",
    date: "2025-05-06",
    course: "Data Structures",
    module: "Array",
    batch: "Batch A",
    time: "9:00 AM",
  },
  {
    _id: "5",
    date: "2025-04-10",
    course: "MongoDB Essentials",
    module: "Indexing",
    batch: "Batch D",
    time: "3:00 PM",
  },
  {
    _id: "6",
    date: "2025-04-11",
    course: "Node.js Advanced",
    module: "Async Await",
    batch: "Batch A",
    time: "12:00 PM",
  },
  {
    _id: "7",
    date: "2025-04-26",
    course: "Next.js 15",
    module: "Dynamic Routing",
    batch: "Batch B",
    time: "10:00 AM",
  },
];

export const ongoingCourses = [
  {
    courseName: "JavaScript Bootcamp",
    batchName: "Batch A",
    lectureNumber: 12,
    module: "Promise",
    instructor: "Mr. Arman Patel",
  },
  {
    courseName: "React.js Mastery",
    batchName: "Batch B",
    lectureNumber: 8,
    module: "useState",
    instructor: "Ms. Robin Teach",
  },
  {
    courseName: "Python for Data Science",
    batchName: "Batch C",
    lectureNumber: 5,
    module: "Datatypes",
    instructor: "Mr. Zoro Bytes",
  },
  {
    courseName: "MongoDB Essentials",
    batchName: "Batch D",
    lectureNumber: 15,
    module: "Indexing",
    instructor: "Dr. Nami Data",
  },
  {
    courseName: "Node.js API Development",
    batchName: "Batch E",
    lectureNumber: 9,
    module: "Dynamic Routing",
    instructor: "Sanji Dev",
  },
];

export const coursesData: Course[] = [
  {
    id: "1",
    name: "JavaScript Bootcamp",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    createdAt: "2024-04-10",
    students: 120,
    discount: 10,
    batches: 5,
    batchesCompleted: 2,
    price: 1000,

    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
  {
    id: "2",
    name: "React Essentials",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",

    createdAt: "2024-03-15",
    students: 80,
    batches: 3,
    discount: 20,
    batchesCompleted: 2,
    price: 1000,
    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
  {
    id: "3",
    name: "Data Structures",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",

    createdAt: "2024-02-05",
    students: 60,
    batches: 4,
    discount: 40,
    batchesCompleted: 2,
    price: 1000,
    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
  {
    id: "4",
    name: "Python Mastery",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",

    createdAt: "2024-01-22",
    students: 100,
    batches: 6,
    batchesCompleted: 1,
    price: 1000,
    discount: 50,
    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
  {
    id: "5",
    name: "MongoDB Crash Course",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",

    createdAt: "2024-01-10",
    students: 70,
    batches: 2,
    discount: 80,
    batchesCompleted: 2,
    price: 1000,
    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
  {
    id: "6",
    name: "Fullstack Development",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",

    createdAt: "2024-01-02",
    students: 90,
    discount: 23,
    batches: 5,
    batchesCompleted: 4,
    price: 1000,
    modules: ["Introduction", "Variables", "Functions", "Objects", "Arrays"],
    batchesName: ["Batch A", "Batch B", "Batch C"],
    instructors: ["Arman Patel", "Robin Teach"],
  },
];
export const dummyInstructors: DummyInstructors[] = [
  {
    id: 1,
    name: "John Doe",
    role: "Lead Instructor",
    avatar: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?q=80&w=2266&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "john@example.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Assistant Instructor",
    avatar: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?q=80&w=2266&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "jane@example.com",
  },
  {
    id: 3,
    name: "Robert Johnson",
    role: "Teaching Assistant",
    avatar: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?q=80&w=2266&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "robert@example.com",
  },
];
export const dummyBatches: DummyBatches[] = [
  {
    id: '1',
    name: "Morning Batch",
    schedule: "Mon-Wed-Fri",
    time: "9:00 AM - 11:00 AM",
    students: 25,
    startDate: "May 15, 2025",
    endDate: "Aug 15, 2025",
    status: "Ongoing",
  },
  {
    id: "2",
    name: "Evening Batch",
    schedule: "Tue-Thu",
    time: "6:00 PM - 8:30 PM",
    students: 18,
    startDate: "June 1, 2025",
    endDate: "Sep 1, 2025",
    status: "Ongoing",
  },
  {
    id: "3",
    name: "Weekend Batch",
    schedule: "Sat-Sun",
    time: "10:00 AM - 2:00 PM",
    students: 22,
    startDate: "May 20, 2025",
    endDate: "Aug 20, 2025",
    status: "Ongoing",
  },
  {
    id: "4",
    name: "Weekend Batch",
    schedule: "Sat-Sun",
    time: "10:00 AM - 2:00 PM",
    students: 22,
    startDate: "May 20, 2025",
    endDate: "Aug 20, 2025",
    status: "Ongoing",
  },
];

export const dummyStudents: DummyStudent[] = [
  {
    id: "stu-1",
    name: "Aarav Mehta",
    email: "aarav@example.com",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    phone: "9876543210",
    batchId: "batch-101",
    isApproved: true,
    joinedAt: "2025-05-01",
    modules: ["HTML", "CSS", "JS"],
    courses: [coursesData[0]],
    feesStatus: "paid",
    totalFeePaid: 20000,
    feesRemaining: 0,
  },
  {
    id: "stu-2",
    name: "Isha Rao",
    email: "isha@example.com",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    phone: "9123456780",
    batchId: "1",
    isApproved: true,
    joinedAt: "2025-05-02",
    modules: ["React", "Node"],
    courses: [coursesData[0]],
    feesStatus: "unpaid",
    totalFeePaid: 10000,
    feesRemaining: 10000,
  },
  {
    id: "stu-3",
    name: "Kabir Joshi",
    email: "kabir@example.com",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    phone: "9988776655",
    batchId: "3",
    isApproved: false,
    joinedAt: "2025-05-03",
    modules: ["Arrays", "Trees"],
    courses: [coursesData[1]],
    feesStatus: "unpaid",
    totalFeePaid: 5000,
    feesRemaining: 10000,
  },
  {
    id: "stu-4",
    name: "Meera Kulkarni",
    email: "meera@example.com",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    phone: "9090909090",
    batchId: "1",
    isApproved: true,
    joinedAt: "2025-05-04",
    modules: ["HTML", "CSS", "JS", "React"],
    courses: [coursesData[0]],
    feesStatus: "paid",
    totalFeePaid: 20000,
    feesRemaining: 0,
  },
  {
    id: "stu-5",
    name: "Rohan Bhat",
    email: "rohan@example.com",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    phone: "8888888888",
    batchId: "1",
    isApproved: true,
    joinedAt: "2025-05-05",
    modules: ["Graphs", "Trees"],
    courses: [coursesData[1]],
    feesStatus: "unpaid",
    totalFeePaid: 7500,
    feesRemaining: 7500,
  }
];
